// Generated by CoffeeScript 1.6.3
(function() {
  var SortAlgorithm, i, nums, sort;

  SortAlgorithm = (function() {
    function SortAlgorithm() {}

    SortAlgorithm.prototype.bubbleSort = function(nums) {
      var i, j, tmp, _i, _j, _nums, _ref, _ref1, _ref2;
      _nums = nums.slice(0);
      for (i = _i = 0, _ref = _nums.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        for (j = _j = _ref1 = i + 1, _ref2 = _nums.length; _ref1 <= _ref2 ? _j <= _ref2 : _j >= _ref2; j = _ref1 <= _ref2 ? ++_j : --_j) {
          if (_nums[i] > _nums[j]) {
            tmp = _nums[i];
            _nums[i] = _nums[j];
            _nums[j] = tmp;
          }
        }
      }
      return _nums;
    };

    return SortAlgorithm;

  })();

  sort = new SortAlgorithm;

  nums = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i < 10; i = ++_i) {
      _results.push(Math.floor(Math.random() * 10));
    }
    return _results;
  })();

  console.log(sort.bubbleSort(nums));

}).call(this);
